### ISSUE TITLE
train.json and val.json?

### ISSUE THREAD

**Issue by jinzhenmu** [kuldeepbrd1/HRNet-spacecraft-pose#1]
hi, can u share yours train.json and val.json of SPEED?

**Comment by kuldeepbrd1** [comment]
Unfortunately, 
Before sharing the processed SPEED data, I'd have to make license changes to this repo. I hope to do it sometime.

In the mean time you can generate your own, using the SPEED annotations provided with the dataset:
https://kelvins.esa.int/satellite-pose-estimation-challenge/data/

I've updated [convert2COCO.py](https://github.com/kuldeepbrd1/HRNet-spacecraft-pose/blob/master/COCO%20Convert/convert2COCO.py) and added [dataset_coco_preprocess.ipynb](https://github.com/kuldeepbrd1/HRNet-spacecraft-pose/blob/master/COCO%20Convert/dataset_coco_preprocess.ipynb). 

Together with minimal modifications, you should be able to generate your own COCO train and val annotations.
